language: android
jdk: oraclejdk7

notifications:
  slack:
    rooms:
      - toastedsnackbar:fiMajiRqVFuYHWQPmjV3afhB#travis-ci

android:
    components:
        - build-tools-23.0.1
        - android-23
        - extra-android-support
        - extra-android-m2repository
        - extra-google-m2repository

script:
    - ./gradlew clean test
